import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "rgba(0,102,245,1)",
  },
  logoImage: {
    width: 160,
    height: 48,
    marginTop: 173,
    alignSelf: "center",
  },
  blueBottonViewStyle: {
    height: 42,
    width: 202,
    position: "absolute",
    left: 0,
    top: 0,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: "#fff",
    backgroundColor: "#fff",
  },
  buttonGoogleIcon: {
    top: 11,
    left: 11,
    marginLeft: -10,
    width: 31,
    height: 22,
    position: "absolute",
  },
  whiteBottonTextStyle: {
    width: 202,
    height: 42,
    marginTop: 59,
    alignSelf: "center",
  },
  whiteButtonStyle_one: {
    height: 43,
    width: 204,
    backgroundColor: "rgba(0,102,245,1)",
    shadowColor: "rgba(0,0,0,1)",
    borderRadius: 5,
    borderWidth: 2,
    borderColor: "#fff",
    shadowOffset: {
      width: 3,
      height: 9,
    },
    elevation: 5,
    shadowOpacity: 0.5,
    shadowRadius: 5,
    marginTop: 33,
    alignSelf: "center",
  },
  whiteButtonStyle_two: {
    padding: 10,
    height: 43,
    width: 230,
    borderRadius: 5,
    borderColor: "#fff",
    borderWidth: 2,
    backgroundColor: "rgba(0,102,245,1)",
    shadowColor: "rgba(0,0,0,1)",
    shadowOffset: {
      height: 9,
      width: 9,
    },
    elevation: 5,
    shadowOpacity: 0.38,
    shadowRadius: 0,
    overflow: "visible",
    marginTop: 30,
    marginLeft: 67,
  },
  loremIpsum: {
    color: "#ADBACD",
  },
  login: {
    color: "rgba(255,255,255,1)",
    lineHeight: 19,
    fontSize: 15,
    fontWeight: "bold",
    marginLeft: 2,
  },
  loremIpsumRow: {
    height: 17,
    flexDirection: "row",
    marginTop: 50,
    alignSelf: "center",
  },
});
